#!/usr/bin/env bash
set -euo pipefail
command -V gh mktemp grep >/dev/null

while getopts 'ds:v' Opts; do
    case "$Opts" in
        d)  set -x ;;
        s)  Suffix="$OPTARG" ;;
        v)  Verbose=1 ;;
        *)  cat <<'end_of_help'
Usage: gh epmi owner1/repo1==v0.9.0 owner2/repo2
Optional arguments:
     -d              Enable debug mode.
     -s .x86_64.rpm  Filter filenames by suffix. Using autodetection by default.
     -v              Enable verbose mode.
end_of_help
            exit ;;
    esac
done
shift $(( "$OPTIND" - 1 ))

: "${Suffix:=.$( uname --machine ).$( epm print info --package-type )}"
TmpDir="$( mktemp --directory )"

for RepoTag in "$@"; do
    mapfile -t -d '=' RepoTagArr < <(echo -n "$RepoTag")
    Repo="${RepoTagArr[0]}"
    if [ "${#RepoTagArr[@]}" != 1 ]; then
        Tag="${RepoTagArr[2]}"
    else
        Tag="$( PAGER='' gh api "repos/$Repo/releases" --jq '.[0].tag_name' )"
    fi
    AssetQuery='.[] | select(.tag_name == "'"$Tag"'") | .assets[]'
    Title="Downloading file *$Suffix with release tag $Tag from repo $Repo"
    test -n "${Verbose:-}" && echo "$Title"

    mapfile -t Assets < <(
        PAGER='' gh api "repos/$Repo/releases" \
            --jq "$AssetQuery"' | select( .name|endswith("'"$Suffix"'") ).name'
    )
    if [ "${#Assets[@]}" -gt 1 ]; then
        echo "Filtered more than one assets. $Title failed!" >&2
        printf '%s\n' "${Assets[@]}" >&2
        exit 1
    elif [ "${#Assets[@]}" -eq 0 ]; then
        echo "Suffix $Suffix not found in assets. $Title failed!" >&2
        PAGER='' gh api "repos/$Repo/releases" --jq "$AssetQuery.name" >&2
        exit 2
    fi
    # Does it use: sha256.txt checksums.txt checksums.txt.pem checksums.txt.sig
    gh release download "$Tag" \
        --dir "$TmpDir" \
        --repo "$Repo" \
        --pattern "*$Suffix"
done
mapfile -t Downloaded < <( find "$TmpDir" -type f -name "*$Suffix" )
epm install --repack "${Downloaded[@]}"
